services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=unitech_task_db'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=unitech'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: