server:
  port: 8080
  servlet:
    application-display-name: unitech_test_task

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/unitech_task_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: &username ${DB_CONNECTION_USERNAME:unitech}
    password: &password ${DB_CONNECTION_PASSWORD:password}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update